# Generated by https://quicktype.io

from datetime import datetime


class Pasaporte():
    id:int
    pasaporte:str
    cedula:str
    expediente:str
    cedulatutor:str
    tarjetaResidencia:str
    OtroDocumento:str
    nombre:str
    apellido:str
    apellido2:str
    sexo:int
    FechaNacimiento:datetime
    FechaPasaporte:datetime
    FechaExpiracion:datetime
    NumeroLibreta:str
    DocumentImage:bytearray
    fingerimage1:bytearray
    fingerimage2:bytearray
    FechaCreado:bytearray
    

    def __init__(self,id,pasaporte = '',cedula = '',expediente = '',cedulatutor = '',tarjetaResidencia= '',OtroDocumento ='',nombre ='',apellido= '',apellido2 = '',sexo = '',FechaNacimiento = '',FechaPasaporte = '',FechaExpiracion = '',NumeroLibreta = '',DocumentImage= '',fingerimage1 = '',fingerimage2 = '',FechaCreado = ''):

        self.id=id
        self.pasaporte=pasaporte
        self.cedula =cedula
        self.expediente =expediente
        self.cedulatutor = cedulatutor
        self.tarjetaResidencia= tarjetaResidencia
        self.OtroDocumento =OtroDocumento
        self.nombre =nombre
        self.apellido=apellido
        self.apellido2 =apellido2
        self.sexo = sexo
        self.FechaNacimiento =FechaNacimiento 
        self.FechaPasaporte = FechaPasaporte
        self.FechaExpiracion = FechaExpiracion
        self.NumeroLibreta = NumeroLibreta
        self.DocumentImage= DocumentImage
        self.fingerimage1 = fingerimage1
        self.fingerimage2 = fingerimage2
        self.FechaCreado = FechaCreado
        


