# Generated by https://quicktype.io

from datetime import datetime
from typing import List


class PersonaPy:
    id_tipoidentificacion: int
    numero: str
    respuesta: str
    nombres: str
    apellido1: str
    apellido2: str
    fh_nac: datetime
    lugar_nacimiento: str
    id_nacionalidad: int
    literal_nacionalidad: str
    sexo: int
    literal_sexo: str
    url_foto: str
    telefonos: List[str]
    correos: List[str]
    codigo_ocupacion: int
    estado_civil: str
    apellido1_padre: str
    fecha_expiracion: datetime
    razon_cancelacion: None
    literal_ocupacion: str
    literal_piel: None
    literal_sangre: str

    def __init__(self, id_tipoidentificacion: int, numero: str, respuesta: str, nombres: str, apellido1: str, apellido2: str, fh_nac: datetime, lugar_nacimiento: str, id_nacionalidad: int, literal_nacionalidad: str, sexo: int, literal_sexo: str, url_foto: str, telefonos: List[str], correos: List[str], codigo_ocupacion: int, estado_civil: str, apellido1_padre: str, fecha_expiracion: datetime, razon_cancelacion: None, literal_ocupacion: str, literal_piel: None, literal_sangre: str) -> None:
        self.id_tipoidentificacion = id_tipoidentificacion
        self.numero = numero
        self.respuesta = respuesta
        self.nombres = nombres
        self.apellido1 = apellido1
        self.apellido2 = apellido2
        self.fh_nac = fh_nac
        self.lugar_nacimiento = lugar_nacimiento
        self.id_nacionalidad = id_nacionalidad
        self.literal_nacionalidad = literal_nacionalidad
        self.sexo = sexo
        self.literal_sexo = literal_sexo
        self.url_foto = url_foto
        self.telefonos = telefonos
        self.correos = correos
        self.codigo_ocupacion = codigo_ocupacion
        self.estado_civil = estado_civil
        self.apellido1_padre = apellido1_padre
        self.fecha_expiracion = fecha_expiracion
        self.razon_cancelacion = razon_cancelacion
        self.literal_ocupacion = literal_ocupacion
        self.literal_piel = literal_piel
        self.literal_sangre = literal_sangre
